const ADD = 'ADD';
const SUB = 'SUB';
const ADD_NUMBER = 'NUM';
const ADD2 = 'ADD2';
const ADD_BOARD = 'ADD_BOARD';
const ADD_COLUMN = 'ADD_COLUMN';
const ADD_CARD = 'ADD_CARD';
const MOVE_COLUMN = 'MOVE_COLUMN';
const MOVE_CARD = 'MOVE_CARD';
const SET_DRAGGED_ITEM = 'SET_DRAGGED_ITEM';
const DELETE_CARD = 'DELETE_CARD';
const DELETE_COLUMN = 'DELETE_COLUMN';
const DELETE_BOARD = 'DELETE_BOARD';
const CHANGE_TEXT = 'CHANGE_TEXT';
const CHANGE_CARD_TITLE = 'CHANGE_CARD_TITLE';
const CHANGE_COLUMN_TITLE = 'CHANGE_COLUMN_TITLE';
const CHANGE_CARD_PRIORITY = 'CHANGE_CARD_PRIORITY';
const CHANGE_CARD_DATE = 'CHANGE_CARD_DATE';

const CHANGE_COLUMN_PRIORITY = 'CHANGE_COLUMN_PRIORITY';
const SET_AUTH_TRUE = 'SET_AUTH_TRUE';
const SET_AUTH_FALSE = 'SET_AUTH_FALSE';
const SET_DISABLE_FALSE = 'SET_DISABLE_FALSE';
const SET_DISABLE_TRUE = 'SET_DISABLE_TRUE';
const TOGGLE_DISABLE = 'TOGGLE_DISABLE';
const SET_CURRENT_BOARD = 'SET_CURRENT_BOARD';

export {
  CHANGE_CARD_DATE,
  CHANGE_CARD_PRIORITY,
  CHANGE_CARD_TITLE,
  CHANGE_COLUMN_PRIORITY,
  CHANGE_COLUMN_TITLE,
  SET_CURRENT_BOARD,
  ADD,
  SUB,
  ADD_NUMBER,
  ADD2,
  ADD_BOARD,
  ADD_COLUMN,
  ADD_CARD,
  MOVE_COLUMN,
  MOVE_CARD,
  SET_DRAGGED_ITEM,
  DELETE_CARD,
  DELETE_COLUMN,
  DELETE_BOARD,
  CHANGE_TEXT,
  SET_AUTH_TRUE,
  SET_AUTH_FALSE,
  SET_DISABLE_FALSE,
  SET_DISABLE_TRUE,
  TOGGLE_DISABLE
};
